# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=63, unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date_published')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
                'verbose_name': 'blog post',
            },
        ),
    ]
