# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20160621_2305'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='startups',
            field=models.ManyToManyField(to='organizer.Startup'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag'),
        ),
    ]
